export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const ADD_LOCATION = "ADD_LOCATION";
